/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  tagline: string;
  monogram?: string;
  primaryCta: CallToAction;
  navigation?: Array<{
    _key: string;
  } & NavigationItem>;
  phone?: string;
  email?: string;
  address?: string;
  mapUrl?: string;
  officeHours?: string;
  socialLinks?: Array<{
    _key: string;
  } & NavigationItem>;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: CmsImage;
};

export type CallToAction = {
  _type: "callToAction";
  label: string;
  href: string;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: PageHero;
  closingCta?: PageHero;
  seo?: Seo;
};

export type PageHero = {
  _type: "pageHero";
  eyebrow?: string;
  title: string;
  description?: string;
  image?: CmsImage;
  cta?: CallToAction;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  eyebrow?: string;
  summary: string;
  heroImage?: CmsImage;
  body: RichText;
  features?: Array<string>;
  faqTitle?: string;
  faqs?: Array<{
    _key: string;
  } & FaqItem>;
  cta?: CallToAction;
  orderRank?: number;
  seo?: Seo;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & InlineImage>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CmsImage = {
  _type: "cmsImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type PricingPage = {
  _id: string;
  _type: "pricingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: PageHero;
  plans?: Array<{
    _key: string;
  } & PricingPlan>;
  note?: string;
  closingCta?: PageHero;
  seo?: Seo;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage?: CmsImage;
  publishedAt: string;
  body: RichText;
  seo?: Seo;
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: PageHero;
  introductionEyebrow?: string;
  introductionTitle: string;
  introductionText: string;
  servicesEyebrow?: string;
  servicesTitle: string;
  servicesDescription?: string;
  servicesCta?: CallToAction;
  featuredServices?: Array<{
    _key: string;
  } & ServiceReference>;
  timelineEyebrow?: string;
  timelineTitle: string;
  timelineDescription?: string;
  timeline?: Array<{
    _key: string;
  } & TimelineStep>;
  valuesTitle: string;
  values?: Array<{
    _key: string;
  } & ValueItem>;
  faqTitle: string;
  faqDescription?: string;
  faqCta?: CallToAction;
  faqs?: Array<{
    _key: string;
  } & FaqItem>;
  articlesTitle: string;
  articlesDescription?: string;
  articlesCta?: CallToAction;
  closingCta?: PageHero;
  seo?: Seo;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: PageHero;
  faqs?: Array<{
    _key: string;
  } & FaqItem>;
  closingCta?: PageHero;
  seo?: Seo;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: PageHero;
  form: ContactFormCopy;
  contactNote?: string;
  seo?: Seo;
};

export type ContactFormCopy = {
  _type: "contactFormCopy";
  heading: string;
  description?: string;
  nameLabel: string;
  emailLabel: string;
  subjectLabel: string;
  messageLabel: string;
  submitLabel: string;
};

export type BlogPage = {
  _id: string;
  _type: "blogPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: PageHero;
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: PageHero;
  storyEyebrow?: string;
  storyTitle: string;
  story: RichText;
  portrait?: CmsImage;
  valuesTitle: string;
  values?: Array<{
    _key: string;
  } & ValueItem>;
  stats?: Array<{
    _key: string;
  } & Stat>;
  closingCta?: PageHero;
  seo?: Seo;
};

export type ValueItem = {
  _type: "valueItem";
  title: string;
  description: string;
};

export type TimelineStep = {
  _type: "timelineStep";
  title: string;
  description: string;
};

export type Stat = {
  _type: "stat";
  value: string;
  label: string;
};

export type PricingPlan = {
  _type: "pricingPlan";
  name: string;
  price: string;
  description: string;
  features?: Array<string>;
  cta?: CallToAction;
  featured?: boolean;
};

export type NavigationItem = {
  _type: "navigationItem";
  label: string;
  href: string;
};

export type InlineImage = {
  _type: "inlineImage";
  image: CmsImage;
  caption?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question: string;
  answer: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Settings | Seo | CallToAction | ServicesPage | PageHero | Service | RichText | SanityImageAssetReference | CmsImage | Slug | PricingPage | Post | ServiceReference | HomePage | FaqPage | ContactPage | ContactFormCopy | BlogPage | AboutPage | ValueItem | TimelineStep | Stat | PricingPlan | NavigationItem | InlineImage | FaqItem | SanityImageCrop | SanityImageHotspot | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_id == "settings"][0]{    siteLogo,    siteName,    tagline,    monogram,    primaryCta{label, href},    navigation[]{_key, label, href},    phone,    email,    address,    mapUrl,    officeHours,    socialLinks[]{_key, label, href},    seo{title, description, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}  }
export type SETTINGS_QUERY_RESULT = {
  siteLogo: null;
  siteName: null;
  tagline: null;
  monogram: null;
  primaryCta: null;
  navigation: null;
  phone: null;
  email: null;
  address: null;
  mapUrl: null;
  officeHours: null;
  socialLinks: null;
  seo: null;
} | {
  siteLogo: null;
  siteName: null;
  tagline: null;
  monogram: null;
  primaryCta: null;
  navigation: null;
  phone: null;
  email: null;
  address: null;
  mapUrl: null;
  officeHours: null;
  socialLinks: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  siteLogo: null;
  siteName: string;
  tagline: string;
  monogram: string | null;
  primaryCta: {
    label: string;
    href: string;
  };
  navigation: Array<{
    _key: string;
    label: string;
    href: string;
  }> | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  mapUrl: string | null;
  officeHours: string | null;
  socialLinks: Array<{
    _key: string;
    label: string;
    href: string;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    hero{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}},    decorativeSignature,    introductionEyebrow,    introductionTitle,    introductionText,    servicesEyebrow,    servicesTitle,    servicesDescription,    servicesCta{label, href},    featuredServices[]->{_id, title, "slug": slug.current, eyebrow, summary, heroImage{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}, orderRank},    timelineEyebrow,    timelineTitle,    timelineDescription,    timeline[]{_key, title, description},    valuesTitle,    values[]{_key, title, description},    faqTitle,    faqDescription,    faqCta{label, href},    faqs[]{_key, question, answer},    articlesTitle,    articlesDescription,    articlesCta{label, href},    "latestPosts": *[_type == "post" && defined(slug.current)] | order(publishedAt desc)[0...3]{_id, title, "slug": slug.current, excerpt, publishedAt, mainImage{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}},    closingCta{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}},    seo{title, description, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}  }
export type HOME_PAGE_QUERY_RESULT = {
  hero: null;
  decorativeSignature: null;
  introductionEyebrow: null;
  introductionTitle: null;
  introductionText: null;
  servicesEyebrow: null;
  servicesTitle: null;
  servicesDescription: null;
  servicesCta: null;
  featuredServices: null;
  timelineEyebrow: null;
  timelineTitle: null;
  timelineDescription: null;
  timeline: null;
  valuesTitle: null;
  values: null;
  faqTitle: null;
  faqDescription: null;
  faqCta: null;
  faqs: null;
  articlesTitle: null;
  articlesDescription: null;
  articlesCta: null;
  latestPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    mainImage: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  }>;
  closingCta: null;
  seo: null;
} | {
  hero: null;
  decorativeSignature: null;
  introductionEyebrow: null;
  introductionTitle: null;
  introductionText: null;
  servicesEyebrow: null;
  servicesTitle: null;
  servicesDescription: null;
  servicesCta: null;
  featuredServices: null;
  timelineEyebrow: null;
  timelineTitle: null;
  timelineDescription: null;
  timeline: null;
  valuesTitle: null;
  values: null;
  faqTitle: null;
  faqDescription: null;
  faqCta: null;
  faqs: null;
  articlesTitle: null;
  articlesDescription: null;
  articlesCta: null;
  latestPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    mainImage: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  }>;
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  decorativeSignature: null;
  introductionEyebrow: null;
  introductionTitle: null;
  introductionText: null;
  servicesEyebrow: null;
  servicesTitle: null;
  servicesDescription: null;
  servicesCta: null;
  featuredServices: null;
  timelineEyebrow: null;
  timelineTitle: null;
  timelineDescription: null;
  timeline: null;
  valuesTitle: null;
  values: null;
  faqTitle: null;
  faqDescription: null;
  faqCta: null;
  faqs: null;
  articlesTitle: null;
  articlesDescription: null;
  articlesCta: null;
  latestPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    mainImage: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  }>;
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: null;
  decorativeSignature: null;
  introductionEyebrow: null;
  introductionTitle: null;
  introductionText: null;
  servicesEyebrow: null;
  servicesTitle: null;
  servicesDescription: null;
  servicesCta: null;
  featuredServices: null;
  timelineEyebrow: null;
  timelineTitle: null;
  timelineDescription: null;
  timeline: null;
  valuesTitle: null;
  values: null;
  faqTitle: string | null;
  faqDescription: null;
  faqCta: null;
  faqs: Array<{
    _key: string;
    question: string;
    answer: string;
  }> | null;
  articlesTitle: null;
  articlesDescription: null;
  articlesCta: null;
  latestPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    mainImage: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  }>;
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  decorativeSignature: null;
  introductionEyebrow: null;
  introductionTitle: null;
  introductionText: null;
  servicesEyebrow: null;
  servicesTitle: null;
  servicesDescription: null;
  servicesCta: null;
  featuredServices: null;
  timelineEyebrow: null;
  timelineTitle: null;
  timelineDescription: null;
  timeline: null;
  valuesTitle: null;
  values: null;
  faqTitle: null;
  faqDescription: null;
  faqCta: null;
  faqs: null;
  articlesTitle: null;
  articlesDescription: null;
  articlesCta: null;
  latestPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    mainImage: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  }>;
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  decorativeSignature: null;
  introductionEyebrow: null;
  introductionTitle: null;
  introductionText: null;
  servicesEyebrow: null;
  servicesTitle: null;
  servicesDescription: null;
  servicesCta: null;
  featuredServices: null;
  timelineEyebrow: null;
  timelineTitle: null;
  timelineDescription: null;
  timeline: null;
  valuesTitle: string;
  values: Array<{
    _key: string;
    title: string;
    description: string;
  }> | null;
  faqTitle: null;
  faqDescription: null;
  faqCta: null;
  faqs: null;
  articlesTitle: null;
  articlesDescription: null;
  articlesCta: null;
  latestPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    mainImage: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  }>;
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  decorativeSignature: null;
  introductionEyebrow: null;
  introductionTitle: null;
  introductionText: null;
  servicesEyebrow: null;
  servicesTitle: null;
  servicesDescription: null;
  servicesCta: null;
  featuredServices: null;
  timelineEyebrow: null;
  timelineTitle: null;
  timelineDescription: null;
  timeline: null;
  valuesTitle: null;
  values: null;
  faqTitle: null;
  faqDescription: null;
  faqCta: null;
  faqs: Array<{
    _key: string;
    question: string;
    answer: string;
  }> | null;
  articlesTitle: null;
  articlesDescription: null;
  articlesCta: null;
  latestPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    mainImage: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  }>;
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  decorativeSignature: null;
  introductionEyebrow: string | null;
  introductionTitle: string;
  introductionText: string;
  servicesEyebrow: string | null;
  servicesTitle: string;
  servicesDescription: string | null;
  servicesCta: {
    label: string;
    href: string;
  } | null;
  featuredServices: Array<{
    _id: string;
    title: string;
    slug: string;
    eyebrow: string | null;
    summary: string;
    heroImage: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
    orderRank: number | null;
  }> | null;
  timelineEyebrow: string | null;
  timelineTitle: string;
  timelineDescription: string | null;
  timeline: Array<{
    _key: string;
    title: string;
    description: string;
  }> | null;
  valuesTitle: string;
  values: Array<{
    _key: string;
    title: string;
    description: string;
  }> | null;
  faqTitle: string;
  faqDescription: string | null;
  faqCta: {
    label: string;
    href: string;
  } | null;
  faqs: Array<{
    _key: string;
    question: string;
    answer: string;
  }> | null;
  articlesTitle: string;
  articlesDescription: string | null;
  articlesCta: {
    label: string;
    href: string;
  } | null;
  latestPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    mainImage: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  }>;
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage"][0]{    hero{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}},    storyEyebrow,    storyTitle,    story,    portrait{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }},    valuesTitle,    values[]{_key, title, description},    stats[]{_key, value, label},    closingCta{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}},    seo{title, description, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}  }
export type ABOUT_PAGE_QUERY_RESULT = {
  hero: null;
  storyEyebrow: null;
  storyTitle: null;
  story: null;
  portrait: null;
  valuesTitle: null;
  values: null;
  stats: null;
  closingCta: null;
  seo: null;
} | {
  hero: null;
  storyEyebrow: null;
  storyTitle: null;
  story: null;
  portrait: null;
  valuesTitle: null;
  values: null;
  stats: null;
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  storyEyebrow: null;
  storyTitle: null;
  story: null;
  portrait: null;
  valuesTitle: null;
  values: null;
  stats: null;
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  storyEyebrow: null;
  storyTitle: null;
  story: null;
  portrait: null;
  valuesTitle: null;
  values: null;
  stats: null;
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  storyEyebrow: null;
  storyTitle: null;
  story: null;
  portrait: null;
  valuesTitle: string;
  values: Array<{
    _key: string;
    title: string;
    description: string;
  }> | null;
  stats: null;
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  storyEyebrow: string | null;
  storyTitle: string;
  story: RichText;
  portrait: {
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  } | null;
  valuesTitle: string;
  values: Array<{
    _key: string;
    title: string;
    description: string;
  }> | null;
  stats: Array<{
    _key: string;
    value: string;
    label: string;
  }> | null;
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: SERVICES_PAGE_QUERY
// Query: *[_id == "servicesPage"][0]{hero{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}, closingCta{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}, seo{title, description, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}}
export type SERVICES_PAGE_QUERY_RESULT = {
  hero: null;
  closingCta: null;
  seo: null;
} | {
  hero: null;
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: BLOG_PAGE_QUERY
// Query: *[_id == "blogPage"][0]{hero{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}, seo{title, description, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}}
export type BLOG_PAGE_QUERY_RESULT = {
  hero: null;
  seo: null;
} | {
  hero: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: PRICING_PAGE_QUERY
// Query: *[_id == "pricingPage"][0]{    hero{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}},    plans[]{_key, name, price, description, features, cta{label, href}, featured},    note,    closingCta{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}},    seo{title, description, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}  }
export type PRICING_PAGE_QUERY_RESULT = {
  hero: null;
  plans: null;
  note: null;
  closingCta: null;
  seo: null;
} | {
  hero: null;
  plans: null;
  note: null;
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  plans: null;
  note: null;
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  plans: null;
  note: null;
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  plans: Array<{
    _key: string;
    name: string;
    price: string;
    description: string;
    features: Array<string> | null;
    cta: {
      label: string;
      href: string;
    } | null;
    featured: boolean | null;
  }> | null;
  note: string | null;
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: FAQ_PAGE_QUERY
// Query: *[_id == "faqPage"][0]{    hero{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}},    faqs[]{_key, question, answer},    closingCta{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}},    seo{title, description, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}  }
export type FAQ_PAGE_QUERY_RESULT = {
  hero: null;
  faqs: null;
  closingCta: null;
  seo: null;
} | {
  hero: null;
  faqs: null;
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  faqs: null;
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: null;
  faqs: Array<{
    _key: string;
    question: string;
    answer: string;
  }> | null;
  closingCta: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  faqs: null;
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  faqs: Array<{
    _key: string;
    question: string;
    answer: string;
  }> | null;
  closingCta: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_id == "contactPage"][0]{    hero{eyebrow, title, description, cta{label, href}, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}},    form{heading, description, nameLabel, emailLabel, subjectLabel, messageLabel, submitLabel},    contactNote,    seo{title, description, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}  }
export type CONTACT_PAGE_QUERY_RESULT = {
  hero: null;
  form: null;
  contactNote: null;
  seo: null;
} | {
  hero: null;
  form: null;
  contactNote: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  form: null;
  contactNote: null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | {
  hero: {
    eyebrow: string | null;
    title: string;
    description: string | null;
    cta: {
      label: string;
      href: string;
    } | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  };
  form: {
    heading: string;
    description: string | null;
    nameLabel: string;
    emailLabel: string;
    subjectLabel: string;
    messageLabel: string;
    submitLabel: string;
  };
  contactNote: string | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: SERVICES_INDEX_QUERY
// Query: *[_type == "service" && defined(slug.current)] | order(orderRank asc, title asc){_id, title, "slug": slug.current, eyebrow, summary, heroImage{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}, orderRank}
export type SERVICES_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  eyebrow: string | null;
  summary: string;
  heroImage: {
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  } | null;
  orderRank: number | null;
}>;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: SERVICE_DETAIL_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    eyebrow,    summary,    heroImage{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }},    body[]{      ...,      _type == "inlineImage" => {image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}, caption}    },    features,    faqTitle,    faqs[]{_key, question, answer},    cta{label, href},    orderRank,    seo{title, description, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}  }
export type SERVICE_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  eyebrow: string | null;
  summary: string;
  heroImage: {
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  } | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "inlineImage";
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    };
    caption: string | null;
  }>;
  features: Array<string> | null;
  faqTitle: string | null;
  faqs: Array<{
    _key: string;
    question: string;
    answer: string;
  }> | null;
  cta: {
    label: string;
    href: string;
  } | null;
  orderRank: number | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: POSTS_INDEX_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){_id, title, "slug": slug.current, excerpt, publishedAt, mainImage{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}
export type POSTS_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  mainImage: {
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: POST_DETAIL_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    mainImage{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }},    body[]{      ...,      _type == "inlineImage" => {image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}, caption}    },    seo{title, description, image{  alt,  crop,  hotspot,  asset->{    _id,    url,    metadata {lqip, dimensions {width, height}}  }}}  }
export type POST_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  mainImage: {
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  } | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "inlineImage";
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    };
    caption: string | null;
  }>;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_id == \"settings\"][0]{\n    siteLogo,\n    siteName,\n    tagline,\n    monogram,\n    primaryCta{label, href},\n    navigation[]{_key, label, href},\n    phone,\n    email,\n    address,\n    mapUrl,\n    officeHours,\n    socialLinks[]{_key, label, href},\n    seo{title, description, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}\n  }\n": SETTINGS_QUERY_RESULT;
    "\n  *[_id == \"homePage\"][0]{\n    hero{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}},\n    decorativeSignature,\n    introductionEyebrow,\n    introductionTitle,\n    introductionText,\n    servicesEyebrow,\n    servicesTitle,\n    servicesDescription,\n    servicesCta{label, href},\n    featuredServices[]->{_id, title, \"slug\": slug.current, eyebrow, summary, heroImage{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}, orderRank},\n    timelineEyebrow,\n    timelineTitle,\n    timelineDescription,\n    timeline[]{_key, title, description},\n    valuesTitle,\n    values[]{_key, title, description},\n    faqTitle,\n    faqDescription,\n    faqCta{label, href},\n    faqs[]{_key, question, answer},\n    articlesTitle,\n    articlesDescription,\n    articlesCta{label, href},\n    \"latestPosts\": *[_type == \"post\" && defined(slug.current)] | order(publishedAt desc)[0...3]{_id, title, \"slug\": slug.current, excerpt, publishedAt, mainImage{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}},\n    closingCta{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}},\n    seo{title, description, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}\n  }\n": HOME_PAGE_QUERY_RESULT;
    "\n  *[_id == \"aboutPage\"][0]{\n    hero{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}},\n    storyEyebrow,\n    storyTitle,\n    story,\n    portrait{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n},\n    valuesTitle,\n    values[]{_key, title, description},\n    stats[]{_key, value, label},\n    closingCta{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}},\n    seo{title, description, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}\n  }\n": ABOUT_PAGE_QUERY_RESULT;
    "\n  *[_id == \"servicesPage\"][0]{hero{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}, closingCta{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}, seo{title, description, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}}\n": SERVICES_PAGE_QUERY_RESULT;
    "\n  *[_id == \"blogPage\"][0]{hero{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}, seo{title, description, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}}\n": BLOG_PAGE_QUERY_RESULT;
    "\n  *[_id == \"pricingPage\"][0]{\n    hero{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}},\n    plans[]{_key, name, price, description, features, cta{label, href}, featured},\n    note,\n    closingCta{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}},\n    seo{title, description, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}\n  }\n": PRICING_PAGE_QUERY_RESULT;
    "\n  *[_id == \"faqPage\"][0]{\n    hero{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}},\n    faqs[]{_key, question, answer},\n    closingCta{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}},\n    seo{title, description, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}\n  }\n": FAQ_PAGE_QUERY_RESULT;
    "\n  *[_id == \"contactPage\"][0]{\n    hero{eyebrow, title, description, cta{label, href}, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}},\n    form{heading, description, nameLabel, emailLabel, subjectLabel, messageLabel, submitLabel},\n    contactNote,\n    seo{title, description, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}\n  }\n": CONTACT_PAGE_QUERY_RESULT;
    "\n  *[_type == \"service\" && defined(slug.current)] | order(orderRank asc, title asc){_id, title, \"slug\": slug.current, eyebrow, summary, heroImage{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}, orderRank}\n": SERVICES_INDEX_QUERY_RESULT;
    "\n  *[_type == \"service\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    eyebrow,\n    summary,\n    heroImage{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n},\n    body[]{\n      ...,\n      _type == \"inlineImage\" => {image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}, caption}\n    },\n    features,\n    faqTitle,\n    faqs[]{_key, question, answer},\n    cta{label, href},\n    orderRank,\n    seo{title, description, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}\n  }\n": SERVICE_DETAIL_QUERY_RESULT;
    "\n  *[_type == \"post\" && defined(slug.current)] | order(publishedAt desc){_id, title, \"slug\": slug.current, excerpt, publishedAt, mainImage{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}\n": POSTS_INDEX_QUERY_RESULT;
    "\n  *[_type == \"post\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    publishedAt,\n    mainImage{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n},\n    body[]{\n      ...,\n      _type == \"inlineImage\" => {image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}, caption}\n    },\n    seo{title, description, image{\n  alt,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions {width, height}}\n  }\n}}\n  }\n": POST_DETAIL_QUERY_RESULT;
  }
}

